[package]
name = "isabelle-plugin-api"
version = "1.5.1"
edition = "2021"

[dependencies]
isabelle-dm = { "git" = "https://github.com/isabelle-platform/isabelle-dm", tag = "1.3.2" }
libloading = "0.8.3"
log = "0.4.0"
