[package]
name = "isabelle-plugin-api"
version = "1.0.3"
edition = "2021"

[dependencies]
isabelle-dm = { "git" = "https://github.com/isabelle-platform/isabelle-dm" }
libloading = "0.8.3"
log = "0.4.0"
